### PR TITLE
Reorganizes values and templates, adds autogenerated secrets (#25)

### PR DESCRIPTION
**Pull request by amorey**
* Places kubetail-related config variables in `values.yaml` under `kubetail` group
* Refactored templates
* Added autogenerated secrets using helm `lookup` command

### CODE REVIEW

**Comment by amorey** [comment]
@nodesocket I made some breaking changes to the helm chart that would be useful to get our opinion on. Here's a snippet from the new [`values.yaml` file](https://github.com/kubetail-org/helm/blob/reorg/charts/kubetail/values.yaml):

```yaml
# -- Overrides the chart's name
nameOverride: null

# -- Override the chart's computed fullname
fullnameOverride: null

# -- Override the release's namespace
namespaceOverride: null

# ###########################################################################################
#
# Base config for kubetail app including kubernetes configurations
#
# ###########################################################################################

kubetail:
  # -- Auth mode lets you specify kubetail's authentication mode
  # There are 3 options:
  # - cluster: Use's cluster RBAC
  # - token: Use's user-provided token
  # - local: Uses local kubectl config
  authMode: cluster

  # -- config file contents (see https://github.com/kubetail-org/kubetail for defaults)
  config: |
    session:
      secret: ${KUBETAIL_CSRF_SECRET}
    csrf:
      secret: ${KUBETAIL_SESSION_SECRET}

  secret:
    # If true, add Secret resource with configured values
    enabled: true
    # -- Overrides the Secret resource name whose default is the chart's computed fullname
    name: null
    # -- Additional annotations
    annotations: {}
    # -- Additional labels
    labels: {}
    # -- base64-encoded secret value for csrf (will be autogenerated if null)
    KUBETAIL_CSRF_SECRET: null
    # -- base64-encoded secret value for session (will be autogenerated if null)
    KUBETAIL_SESSION_SECRET: null

  image:
    # -- Image registry
    registry: docker.io
    # -- Image repository
    repository: kubetail/kubetail
    # -- Overrides the image tag whose default is the chart's appVersion
    tag: null
    # -- Overrides the image tag with an image digest
    digest: null
    # -- Docker image pull policy
    pullPolicy: IfNotPresent

  podTemplate:
    # -- Additional annotations
    annotations: {}
    # -- Additional labels
    labels: {}
    # -- Affinity for pods
    affinity: {}
    # -- AutomountServiceAccounttoken for pods
    automountServiceAccountToken: true
    # -- Additional env
    env: {}
    # -- Additional envFrom
    envFrom: {}
    # -- Additional args
    args: []
    # -- Port number
    port: 4000
    # -- Liveness probe
    livenessProbe:
      httpGet:
        scheme: HTTP
        path: /healthz
        port: kubetail
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    # -- Readiness probe
    readinessProbe:
      httpGet:
        scheme: HTTP
        path: /healthz
        port: kubetail
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    # -- Resources
    resources: {}
    # -- Security context
    securityContext:
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    # -- Kubetail container's security context
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
```

The kubetail-related attributes have been moved to a top-level `kubetail` group in order to accommodate other top-level groups later (loki does this as well). It also changes the `ports` variable to `rules` in the Ingress resource to conform with the manifest's attribute name.

When you get a chance please take a look and let me know what you think of the new chart.

**Comment by nodesocket** [comment]
@amorey can you perhaps just show me what my migrated `values.yaml` would look like using these change?

Current `values.yaml`. Thanks

```
deployment:
  resources:
    requests:
      cpu: 250m
      memory: 64Mi
    limits:
      cpu: 1
config:
  session:
    secret: <random-here>
  csrf:
    secret: <random-here>
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
  hosts:
    - host: kubetail.mydomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - kubetail.mydomain.com
```

**Comment by amorey** [comment]
No prob! This is what the config would be with secrets removed so they'll be auto-generated:

```
kubetail:
  podTemplate:
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 1
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    rules:
    - host: kubetail.mydomain.com
       paths:
       - path: /
          pathType: Prefix
    tls:
    - hosts:
       - kubetail.mydomain.com
```

**Comment by nodesocket** [comment]
@amorey thanks for providing my example. Let me know when this is deployed and I'll test it out.

**Comment by amorey** [comment]
@nodesocket I merged the changes into the main branch and released a new version (0.4.1). I also changed the repo name from 'helm' to 'helm-charts' which shouldn't affect your installation but if you want you can re-add the repo with the new url:

```console
helm repo remove kubetail
helm repo add kubetail https://kubetail-org.github.io/helm-charts/
```

Apologies for the breaking changes, I'm trying to keep them at a minimum. Just a heads up - there will probably be another set of breaking changes to implement search but that won't be ready for a while.

**Pull request merged**
