### PR TITLE
Fixes for ingress

### PR DESCRIPTION
**Pull request by nodesocket**
- Use alias `$ing` instead of `.Values.ingress` in the ingress template.

### CODE REVIEW

**Comment by amorey** [comment]
I tried it out and it works but I'm not sure how since I don't see `$ing` defined anywhere. How is its value being set?

**Comment by nodesocket** [comment]
See the first line in the ingress template? I am essentially creating a shortcut alias for .Value.ingress named $ing. It’s just for readability. Does not fix my issue of using service.name in the ingress.yaml. It should be working as service.name is defined/defaults to empty string in your values.yaml.

**Comment by nodesocket** [comment]
@amorey I'm at a loss here. Even manually setting `service.name` using `--set` is still breaking.

```
helm install kubetail --values values.yaml --set service.name=kubetail kubetail/kubetail
    Error: INSTALLATION FAILED: template: kubetail/templates/ingress.yaml:22:31: executing "kubetail/templates/ingress.yaml" at <.Values.service.name>: nil pointer evaluating interface {}.service
```

My `values.yaml` is simply:

```yaml
deployment:
  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 1
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
  hosts:
    - host: kubetail.mydomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - kubetail.mydomain.com
```

**Comment by amorey** [comment]
> See the first line in the ingress template? I am essentially creating a shortcut alias for .Values.ingress named $ing. It’s just for readability. Does not fix my issue of using service.name in the ingress.yaml. It should be working as service.name is defined/defaults to empty string in your values.yaml.

Ahhh... I see. The first two lines were hidden in the GitHub diff so I couldn't figure out where you were defining `$ing`.

**Comment by amorey** [comment]
I submitted a PR to your fork. If that looks ok you can merge and update the PR here.

**Pull request closed without merging**
